# Generated by Django 2.1.1 on 2018-09-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
