# Generated by Django 2.1.1 on 2018-09-30 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20180929_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperitem',
            name='last_saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperitem',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
